### ISSUE TITLE
doc links are broken

### ISSUE THREAD

**Issue by splaisan** [phac-nml/staramrnf#1]
### Description of feature

can you please fix the links in

For more details and further functionality, please refer to the [usage documentation](https://nf-co.re/staramr/usage) and the [parameter documentation](https://nf-co.re/staramr/parameters).

thanks

**Comment by emarinier** [comment]
Hi!

This nf-core pipeline for StarAMR was a work in progress pipeline and wasn't released. The project was partly motivated by wanting to learning how to develop within nf-core/nextflow.

A lot of the documentation here is placeholder documentation that's automatically generated by nf-core tools. There is no usage or parameter documentation.

Currently, our priorities have shifted to work on other pipelines, but it's possible we may continue to work on this in the new year. Sorry about that!

- Eric

**Comment by sgsutcliffe** [comment]
Sorry for the delay! We continued the development and now have our first release [0.1.0] which hopefully will address your issues. Let us know if you have more questions, otherwise I will close the issue for now.

[0.1.0]: https://github.com/phac-nml/staramrnf/releases/tag/0.1.0
